
services:
  # MySQL 数据库
  mysql:
    image: mysql:8.0
    container_name: myapp-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: fastapi_financial
    ports:
      - "3306:3306" # 可选，如果需要本地连接
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p123456" ]
      timeout: 20s
      retries: 10

  # 后端服务
  backend:
    build: ./test1_backend # 指定后端路径 !!!!!!!!!!!!!!!!!!!!!!!!!
    container_name: myapp-backend
    ports:
      - "8000:8000"
    environment:
      # 从环境变量读取，或者直接写在这里
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456
      - MYSQL_HOST=mysql # 使用服务名
      - MYSQL_PORT=3306
      - MYSQL_DB=fastapi_financial
    env_file:
      - ./test1_backend/.env # 指定文件路径!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped

  # 前端服务
  frontend:
    build: ./test1_frontend # 指定前端路径 !!!!!!!!!!!!!!!!!!!!
    container_name: myapp-frontend
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
