"""add  account_version column to account

Revision ID: 4cf785ee73f8
Revises: 700eb3dfe231
Create Date: 2026-04-07 14:26:22.230654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cf785ee73f8'
down_revision: Union[str, Sequence[str], None] = '700eb3dfe231'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('account_version', sa.String(length=20), nullable=True, comment='科目版本'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'account_version')
    # ### end Alembic commands ###
