"""增加科目表和科目版本表v3

Revision ID: c22ff791d4e6
Revises: c96f59e28b08
Create Date: 2026-04-14 19:29:52.683314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c22ff791d4e6'
down_revision: Union[str, Sequence[str], None] = 'c96f59e28b08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
