"""增加科目表和科目版本表v2

Revision ID: c96f59e28b08
Revises: 026220ec943f
Create Date: 2026-04-14 10:50:41.503669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c96f59e28b08'
down_revision: Union[str, Sequence[str], None] = '026220ec943f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_version',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('version_code', sa.String(length=20), nullable=False, comment='版本编码'),
    sa.Column('version_name', sa.String(length=100), nullable=False, comment='版本名称'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='版本描述'),
    sa.Column('is_default', sa.Boolean(), nullable=True, comment='是否默认版本'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否启用'),
    sa.Column('effective_date', sa.String(length=20), nullable=True, comment='生效日期'),
    sa.Column('remark', sa.String(length=500), nullable=True, comment='版本备注'),
    sa.Column('created_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_version_id'), 'account_version', ['id'], unique=False)
    op.create_index(op.f('ix_account_version_version_code'), 'account_version', ['version_code'], unique=True)
    op.create_table('account',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False, comment='科目编码'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='科目名称'),
    sa.Column('display_name', sa.String(length=100), nullable=True, comment='显示名称'),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='父科目ID'),
    sa.Column('level', sa.Integer(), nullable=True, comment='科目级次 (1=一级, 2=二级...)'),
    sa.Column('is_leaf', sa.Boolean(), nullable=True, comment='是否叶子节点(末级科目)'),
    sa.Column('balance_direction', sa.Enum('DEBIT', 'CREDIT', name='balancedirection'), nullable=True, comment='余额方向'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否启用'),
    sa.Column('full_name', sa.String(length=255), nullable=True, comment='全称路径'),
    sa.Column('account_version_id', sa.Integer(), nullable=False, comment='科目版本ID'),
    sa.Column('created_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['account_version_id'], ['account_version.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'account_version_id', name='uq_account_code_version')
    )
    op.create_index(op.f('ix_account_id'), 'account', ['id'], unique=False)
    op.create_index(op.f('ix_account_parent_id'), 'account', ['parent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_account_parent_id'), table_name='account')
    op.drop_index(op.f('ix_account_id'), table_name='account')
    op.drop_table('account')
    op.drop_index(op.f('ix_account_version_version_code'), table_name='account_version')
    op.drop_index(op.f('ix_account_version_id'), table_name='account_version')
    op.drop_table('account_version')
    # ### end Alembic commands ###
