"""init database

Revision ID: d4fc3f2ad975
Revises: 
Create Date: 2026-04-07 09:35:48.848632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd4fc3f2ad975'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('company_ibfk_2'), 'company', type_='foreignkey')
    op.drop_constraint(op.f('company_ibfk_1'), 'company', type_='foreignkey')
    op.create_foreign_key(None, 'company', 'user', ['created_by'], ['user_id'])
    op.create_foreign_key(None, 'company', 'user', ['updated_by'], ['user_id'])
    op.alter_column('user', 'id',
               existing_type=mysql.BIGINT(),
               comment='自增ID',
               existing_comment='用户ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('user', 'user_id',
               existing_type=mysql.BIGINT(),
               comment='用户ID（雪花算法）',
               existing_comment='用户ID',
               existing_nullable=False)
    op.drop_index(op.f('userid_UNIQUE'), table_name='user')
    op.alter_column('user_role', 'user_id',
               existing_type=mysql.BIGINT(),
               comment='用户ID（雪花算法）',
               existing_comment='用户ID',
               existing_nullable=False)
    op.alter_column('user_role', 'role_id',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               existing_comment='角色ID',
               existing_nullable=False)
    op.create_foreign_key(None, 'user_role', 'role', ['role_id'], ['role_id'], onupdate='CASCADE', ondelete='CASCADE')
    op.alter_column('user_token', 'user_id',
               existing_type=mysql.BIGINT(),
               comment='用户ID（雪花算法）',
               existing_comment='用户ID',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_token', 'user_id',
               existing_type=mysql.BIGINT(),
               comment='用户ID',
               existing_comment='用户ID（雪花算法）',
               existing_nullable=False)
    op.drop_constraint(None, 'user_role', type_='foreignkey')
    op.alter_column('user_role', 'role_id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               existing_comment='角色ID',
               existing_nullable=False)
    op.alter_column('user_role', 'user_id',
               existing_type=mysql.BIGINT(),
               comment='用户ID',
               existing_comment='用户ID（雪花算法）',
               existing_nullable=False)
    op.create_index(op.f('userid_UNIQUE'), 'user', ['user_id'], unique=False)
    op.alter_column('user', 'user_id',
               existing_type=mysql.BIGINT(),
               comment='用户ID',
               existing_comment='用户ID（雪花算法）',
               existing_nullable=False)
    op.alter_column('user', 'id',
               existing_type=mysql.BIGINT(),
               comment='用户ID',
               existing_comment='自增ID',
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'company', type_='foreignkey')
    op.drop_constraint(None, 'company', type_='foreignkey')
    op.create_foreign_key(op.f('company_ibfk_1'), 'company', 'user', ['created_by'], ['user_id'], onupdate='CASCADE', ondelete='SET NULL')
    op.create_foreign_key(op.f('company_ibfk_2'), 'company', 'user', ['updated_by'], ['user_id'], onupdate='CASCADE', ondelete='SET NULL')
    # ### end Alembic commands ###
