"""删除旧科目表

Revision ID: 026220ec943f
Revises: 0204a31c5be6
Create Date: 2026-04-13 18:44:59.663953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '026220ec943f'
down_revision: Union[str, Sequence[str], None] = '0204a31c5be6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_account_code'), table_name='account')
    op.drop_index(op.f('ix_account_id'), table_name='account')
    op.drop_index(op.f('ix_account_parent_id'), table_name='account')
    op.drop_table('account')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', mysql.VARCHAR(length=20), nullable=False, comment='科目编码'),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False, comment='科目名称'),
    sa.Column('parent_id', mysql.INTEGER(), autoincrement=False, nullable=True, comment='父科目ID'),
    sa.Column('level', mysql.INTEGER(), autoincrement=False, nullable=True, comment='科目级次 (1=一级, 2=二级...)'),
    sa.Column('balance_direction', mysql.ENUM('DEBIT', 'CREDIT'), nullable=True, comment='余额方向'),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True, comment='是否启用'),
    sa.Column('full_name', mysql.VARCHAR(length=255), nullable=True, comment='全称路径 (如: 资产/流动资产/货币资金)'),
    sa.Column('created_time', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False, comment='创建时间'),
    sa.Column('updated_time', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False, comment='更新时间'),
    sa.Column('account_version', mysql.VARCHAR(length=20), nullable=True, comment='科目版本'),
    sa.ForeignKeyConstraint(['parent_id'], ['account.id'], name=op.f('account_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_account_parent_id'), 'account', ['parent_id'], unique=False)
    op.create_index(op.f('ix_account_id'), 'account', ['id'], unique=False)
    op.create_index(op.f('ix_account_code'), 'account', ['code'], unique=True)
    # ### end Alembic commands ###
