"""add city

Revision ID: 0a80cb74f850
Revises: 4cf785ee73f8
Create Date: 2026-04-07 15:16:29.492424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a80cb74f850'
down_revision: Union[str, Sequence[str], None] = '4cf785ee73f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('city',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='城市ID'),
    sa.Column('name', sa.String(length=32), nullable=False, comment='城市名称'),
    sa.Column('province', sa.String(length=32), nullable=False, comment='省份'),
    sa.Column('area', sa.String(length=32), nullable=False, comment='区域'),
    sa.Column('category', sa.String(length=32), nullable=False, comment='城市分类'),
    sa.Column('created_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_city_id', 'city', ['id'], unique=True)
    op.create_index('idx_city_name', 'city', ['name'], unique=False)
    op.create_index('idx_city_province', 'city', ['province'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_city_province', table_name='city')
    op.drop_index('idx_city_name', table_name='city')
    op.drop_index('idx_city_id', table_name='city')
    op.drop_table('city')
    # ### end Alembic commands ###
